### ISSUE TITLE
What is the purpose of `allowThunks`?

### ISSUE THREAD

**Issue by remorses** [bhoriuchi/graphql-go-tools#10]
i see that you set `allowThunks` in this line when the `iterations` go over the `maxIteration`, can you explain me what is its usage?

https://github.com/bhoriuchi/graphql-go-tools/blob/fe56277415a18aa8c4a403a8c426f860e64ceac1/registry.go#L253

I had to set `allowThunks` to false because of this issue
https://github.com/graphql-go/graphql/issues/543

**Comment by bhoriuchi** [comment]
It's been a while, but if I remember correctly the code can potentially perform several passes while trying to build types. Each pass builds types with either no dependencies or dependencies that have been met.

This can all be done by just using Thunks for everything on a single pass but if you do that you aren't validating that all the dependencies have been created. So allow thunks is a flag that is set when the code can't resolve a dependent type.

I am open to an alternate approach.

**Comment by bhoriuchi** [comment]
allow thunks has been removed in favor of a pre-build dependency check that identifies the types that will need to use thunks

see https://github.com/bhoriuchi/graphql-go-tools/blob/master/dependencies.go
