### ISSUE TITLE
How to add descriptions for types and fields?

### ISSUE THREAD

**Issue by 425325336** [bhoriuchi/graphql-go-tools#4]
eg-js:
Input
"""
An individual human being.
"""
type Person {
  """
  The full name of the person.
  """
  name: String
  """
  The elapsed time (in years) since the person's birth.
  """
  age: Int
}

output:
const jsonSchema = {
  $id: '#/person',
  type: 'object',
  description: 'An individual human being.',
  properties: {
    name: {
      type: 'string',
      description: 'The full name of the person.',
    },
    age: {
      type: 'integer',
      description: "The elapsed time (in years) since the person's birth.",
    },
  },
}

**Comment by remorses** [comment]
Just use triple quotes

```graphql
type Query {
  """
  description
  """
  simple: String
}
```
